stages:
  data ingestion:
    cmd: python src/mlproject/pipeline/stage_01_data_ingestion.py

    deps: 
      -  config/config.yaml
    
    outs: 
      - artifacts/data_ingestion/data.zip
      - artifacts/data_ingestion/winequality-red.csv

  Data Validation:
    cmd: python src/mlproject/pipeline/stage_02_data_validation.py

    deps:
      - artifacts/data_ingestion/winequality-red.csv
      - schema.yaml

    outs:
      - artifacts/data_validation/status.txt
  Data Transformation:
    cmd: python src/mlproject/pipeline/stage_03_data_transformation.py

    deps:
      - artifacts/data_ingestion/winequality-red.csv
      - config/config.yaml

    outs:
      - artifacts/data_transformation/train.csv
      - artifacts/data_transformation/test.csv

  Model Training:
    cmd : python src/mlproject/pipeline/stage_04_model_trainer.py

    deps:
      - artifacts/data_transformation/train.csv
      - config/config.yaml
      - schema.yaml
      - params.yaml
      
    
    outs:
      - artifacts/model_trainer/model.joblib

  Model Evaluation:
    cmd: python src/mlproject/pipeline/stage_05_model_evaluation.py

    deps:
      - artifacts/model_trainer/model.joblib
      - schema.yaml
      - config/config.yaml
      
    outs:
      - artifacts/model_evaluation/metrics.json